---
title: "Yuchen's Resume"
output: 
  html_document:
    toc: true
    toc_float: true

---

## Education

<p style="text-align:left;">
    **Columbia University, Mailman School of Public Health**, New York, NY 
    <span style="float:right;">
        Expected May 2023  
    </span>
</p>
Master of Science in Biostatistics         
**Relevant Coursework**: Data Science, Biostatistical Methods, Probability    


<p style="text-align:left;">
    **University of California, Santa Barbara**, Goleta, CA 
    <span style="float:right;">
        June 2021  
    </span> 
</p>
Bachelor of Science in Statistics and Data Science    
**Relevant Coursework**: Intro to Computer Science (Python), Principles of Data Science (R and SQL), Statistical Machine Learning (R and PySpark), SAS Base Program, Big Data Analytics (PySpark)    
**Involvement**: Breaching Biotech (Marketing Officer and Events Coordinator), Residential Desk Attendant, Conference and Hospitality Guest Representative

<p style="text-align:left;">
    This text is left aligned
    <span style="float:right;">
        This text is right aligned
    </span>
</p>

## Academic Data Analytics Project
<p style="text-align:left;">
    **Total Vehicle Sales Forecasting March**
    <span style="float:right;">
        March 2021 – June 2021
    </span>
</p>
This project was a Time Series Analysis Project in R. I built a best-fitted Box-Jenkins model for forecasting on total vehicles sales data in the US and successfully predicted the monthly total vehicle sales in 2019 in the U.S. using data from 2010 to 2018

<p style="text-align:left;">
    **Big Data Analytics** 
    <span style="float:right;">
        January 2021 – March 2021
    </span>
</p>
This project was a Bia Data Analytics Project in PySpark. I conducted exploratory data analysis on dataset Trending Youtube Videos and used Natural Language Processing to build and train regression models such as Linear Regression, Random Forest to predict number of trending days for a video. Lastly, I selected best model by comparing model accuracy of each model and reported the findings in a presentation.

<p style="text-align:left;">
    **Machine Learning** 
    <span style="float:right;">
        October 2020 – December 2020
    </span>
</p>
This project was a Machine Learning Project in R. I cleaned and visualized 2020 US Presidential Election Dataset. Classification models such as K-nearest Neighbor Classification, Decision Tree, Random Forest and Logistic Regression were built and trained to predict the election winner. Best model was selected by comparing the testing error and AUC value of each model and reported in a final paper.

<p style="text-align:left;">
    **Survival Analysis of Adjunct Therapy for Colon Cancer** 
    <span style="float:right;">
        October 2020 – December 2020
    </span>
</p>
This project was a Survival Analysis Project in R. I estimated the effect of treatments for patients with colon cancer using Kaplan-Meier estimate, Cox Proportional Hazards Model and studied the relationship between the recurrence rate and the overall survival rate using recurrent event model.

## Research Experience
**UC Santa Barbara, Goleta, CA**
<p style="text-align:left;">
    Briggs Lab Undergraduate Research Assistant
    <span style="float:right;">
        March 2020 - Present 
    </span>
</p>
● Conduct literature reviews to gather information about invasive species distributions   
● Use R to organize species presence data   
● Use Maxent to estimate invasive species' niche and potential geographic distribution   
● Collaborate in a group of 4 for quantitative research project on estimation subject matter     
● Write summary reports and communicate findings in group

## Skills and Abilities
**Language**: Chinese (Native) English (Fluent)    
**Technical**:   
● R, SQL, PowerPoint, Google tools (All Advanced)  
● SAS, Python, PySpark, C++, Microsoft Excel (All Intermediate)  

<a href="Yuchen Zheng Resume .pdf" download="Yuchen Zheng Resume">Download a copy of my resume here</a>

